//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFilmyProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezyser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezyser()
        {
            this.Film = new HashSet<Film>();
        }
    
        public int rezyser_id { get; set; }
        public string data_urodzenia { get; set; }
        public string imie { get; set; }
        public string narodowosc { get; set; }
        public string nazwisko { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Film> Film { get; set; }
        public override string ToString()
        {
            return this.imie + " " + this.nazwisko + " " + this.narodowosc;
        }
    }
}
